// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_plonky2_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-04-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-QR4H5RM`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/dimitris/current_sprint/zkVerify/target/production/zkv-relay
// benchmark
// pallet
// --runtime
// /home/dimitris/current_sprint/zkVerify/target/production/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-plonky2-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/dimitris/current_sprint/zkVerify/HEADER-APACHE2
// --output
// /home/dimitris/current_sprint/zkVerify/verifiers/plonky2/src/weight_verify_proof.rs
// --template
// /home/dimitris/current_sprint/zkVerify/relay-node/benchmarks/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_plonky2_verifier_verify_proof`.
pub trait WeightInfo {
    fn verify_proof_poseidon_compressed_2() -> Weight;
    fn verify_proof_keccak_compressed_2() -> Weight;
    fn verify_proof_poseidon_uncompressed_2() -> Weight;
    fn verify_proof_keccak_uncompressed_2() -> Weight;
    fn verify_proof_poseidon_compressed_3() -> Weight;
    fn verify_proof_keccak_compressed_3() -> Weight;
    fn verify_proof_poseidon_uncompressed_3() -> Weight;
    fn verify_proof_keccak_uncompressed_3() -> Weight;
    fn verify_proof_poseidon_compressed_4() -> Weight;
    fn verify_proof_keccak_compressed_4() -> Weight;
    fn verify_proof_poseidon_uncompressed_4() -> Weight;
    fn verify_proof_keccak_uncompressed_4() -> Weight;
    fn verify_proof_poseidon_compressed_5() -> Weight;
    fn verify_proof_keccak_compressed_5() -> Weight;
    fn verify_proof_poseidon_uncompressed_5() -> Weight;
    fn verify_proof_keccak_uncompressed_5() -> Weight;
    fn verify_proof_poseidon_compressed_6() -> Weight;
    fn verify_proof_keccak_compressed_6() -> Weight;
    fn verify_proof_poseidon_uncompressed_6() -> Weight;
    fn verify_proof_keccak_uncompressed_6() -> Weight;
    fn verify_proof_poseidon_compressed_7() -> Weight;
    fn verify_proof_keccak_compressed_7() -> Weight;
    fn verify_proof_poseidon_uncompressed_7() -> Weight;
    fn verify_proof_keccak_uncompressed_7() -> Weight;
    fn verify_proof_poseidon_compressed_8() -> Weight;
    fn verify_proof_keccak_compressed_8() -> Weight;
    fn verify_proof_poseidon_uncompressed_8() -> Weight;
    fn verify_proof_keccak_uncompressed_8() -> Weight;
    fn verify_proof_poseidon_compressed_9() -> Weight;
    fn verify_proof_keccak_compressed_9() -> Weight;
    fn verify_proof_poseidon_uncompressed_9() -> Weight;
    fn verify_proof_keccak_uncompressed_9() -> Weight;
    fn verify_proof_poseidon_compressed_10() -> Weight;
    fn verify_proof_keccak_compressed_10() -> Weight;
    fn verify_proof_poseidon_uncompressed_10() -> Weight;
    fn verify_proof_keccak_uncompressed_10() -> Weight;
    fn verify_proof_poseidon_compressed_11() -> Weight;
    fn verify_proof_keccak_compressed_11() -> Weight;
    fn verify_proof_poseidon_uncompressed_11() -> Weight;
    fn verify_proof_keccak_uncompressed_11() -> Weight;
    fn verify_proof_poseidon_compressed_12() -> Weight;
    fn verify_proof_keccak_compressed_12() -> Weight;
    fn verify_proof_poseidon_uncompressed_12() -> Weight;
    fn verify_proof_keccak_uncompressed_12() -> Weight;
    fn verify_proof_poseidon_compressed_13() -> Weight;
    fn verify_proof_keccak_compressed_13() -> Weight;
    fn verify_proof_poseidon_uncompressed_13() -> Weight;
    fn verify_proof_keccak_uncompressed_13() -> Weight;
    fn verify_proof_poseidon_compressed_14() -> Weight;
    fn verify_proof_keccak_compressed_14() -> Weight;
    fn verify_proof_poseidon_uncompressed_14() -> Weight;
    fn verify_proof_keccak_uncompressed_14() -> Weight;
    fn verify_proof_poseidon_compressed_15() -> Weight;
    fn verify_proof_keccak_compressed_15() -> Weight;
    fn verify_proof_poseidon_uncompressed_15() -> Weight;
    fn verify_proof_keccak_uncompressed_15() -> Weight;
    fn verify_proof_poseidon_compressed_16() -> Weight;
    fn verify_proof_keccak_compressed_16() -> Weight;
    fn verify_proof_poseidon_uncompressed_16() -> Weight;
    fn verify_proof_keccak_uncompressed_16() -> Weight;
    fn verify_proof_poseidon_compressed_17() -> Weight;
    fn verify_proof_keccak_compressed_17() -> Weight;
    fn verify_proof_poseidon_uncompressed_17() -> Weight;
    fn verify_proof_keccak_uncompressed_17() -> Weight;
    fn verify_proof_poseidon_compressed_18() -> Weight;
    fn verify_proof_keccak_compressed_18() -> Weight;
    fn verify_proof_poseidon_uncompressed_18() -> Weight;
    fn verify_proof_keccak_uncompressed_18() -> Weight;
    fn verify_proof_poseidon_compressed_19() -> Weight;
    fn verify_proof_keccak_compressed_19() -> Weight;
    fn verify_proof_poseidon_uncompressed_19() -> Weight;
    fn verify_proof_keccak_uncompressed_19() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn verify_proof_poseidon_compressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 11_758_830_000 picoseconds.
        Weight::from_parts(12_285_910_000, 0)
    }
    fn verify_proof_keccak_compressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_492_498_000 picoseconds.
        Weight::from_parts(1_786_534_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_985_123_000 picoseconds.
        Weight::from_parts(6_181_171_000, 0)
    }
    fn verify_proof_keccak_uncompressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 819_308_000 picoseconds.
        Weight::from_parts(840_782_000, 0)
    }
    fn verify_proof_poseidon_compressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 13_012_237_000 picoseconds.
        Weight::from_parts(15_029_957_000, 0)
    }
    fn verify_proof_keccak_compressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_591_497_000 picoseconds.
        Weight::from_parts(1_634_786_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_558_027_000 picoseconds.
        Weight::from_parts(7_193_615_000, 0)
    }
    fn verify_proof_keccak_uncompressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 827_989_000 picoseconds.
        Weight::from_parts(852_349_000, 0)
    }
    fn verify_proof_poseidon_compressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 14_082_053_000 picoseconds.
        Weight::from_parts(15_043_519_000, 0)
    }
    fn verify_proof_keccak_compressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_747_495_000 picoseconds.
        Weight::from_parts(1_857_269_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_091_247_000 picoseconds.
        Weight::from_parts(7_730_540_000, 0)
    }
    fn verify_proof_keccak_uncompressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 882_744_000 picoseconds.
        Weight::from_parts(908_408_000, 0)
    }
    fn verify_proof_poseidon_compressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_494_895_000 picoseconds.
        Weight::from_parts(16_747_798_000, 0)
    }
    fn verify_proof_keccak_compressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_844_663_000 picoseconds.
        Weight::from_parts(1_861_431_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_676_522_000 picoseconds.
        Weight::from_parts(7_847_536_000, 0)
    }
    fn verify_proof_keccak_uncompressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 980_442_000 picoseconds.
        Weight::from_parts(1_002_373_000, 0)
    }
    fn verify_proof_poseidon_compressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 19_298_499_000 picoseconds.
        Weight::from_parts(20_675_940_000, 0)
    }
    fn verify_proof_keccak_compressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_976_099_000 picoseconds.
        Weight::from_parts(3_031_151_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 9_510_190_000 picoseconds.
        Weight::from_parts(10_240_384_000, 0)
    }
    fn verify_proof_keccak_uncompressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_630_190_000 picoseconds.
        Weight::from_parts(1_688_845_000, 0)
    }
    fn verify_proof_poseidon_compressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 20_274_486_000 picoseconds.
        Weight::from_parts(22_049_049_000, 0)
    }
    fn verify_proof_keccak_compressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_196_416_000 picoseconds.
        Weight::from_parts(3_278_279_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 10_408_694_000 picoseconds.
        Weight::from_parts(11_820_611_000, 0)
    }
    fn verify_proof_keccak_uncompressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_628_063_000 picoseconds.
        Weight::from_parts(1_678_379_000, 0)
    }
    fn verify_proof_poseidon_compressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 22_138_137_000 picoseconds.
        Weight::from_parts(23_907_559_000, 0)
    }
    fn verify_proof_keccak_compressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_524_723_000 picoseconds.
        Weight::from_parts(3_688_570_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 11_163_774_000 picoseconds.
        Weight::from_parts(12_226_880_000, 0)
    }
    fn verify_proof_keccak_uncompressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_723_450_000 picoseconds.
        Weight::from_parts(1_747_798_000, 0)
    }
    fn verify_proof_poseidon_compressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 24_003_967_000 picoseconds.
        Weight::from_parts(25_085_343_000, 0)
    }
    fn verify_proof_keccak_compressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_623_073_000 picoseconds.
        Weight::from_parts(3_790_491_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 11_904_164_000 picoseconds.
        Weight::from_parts(12_585_845_000, 0)
    }
    fn verify_proof_keccak_uncompressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_819_644_000 picoseconds.
        Weight::from_parts(1_996_085_000, 0)
    }
    fn verify_proof_poseidon_compressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 28_603_380_000 picoseconds.
        Weight::from_parts(30_673_268_000, 0)
    }
    fn verify_proof_keccak_compressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 4_796_365_000 picoseconds.
        Weight::from_parts(5_257_964_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 13_693_794_000 picoseconds.
        Weight::from_parts(14_658_974_000, 0)
    }
    fn verify_proof_keccak_uncompressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_460_530_000 picoseconds.
        Weight::from_parts(2_525_398_000, 0)
    }
    fn verify_proof_poseidon_compressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 29_489_536_000 picoseconds.
        Weight::from_parts(32_932_988_000, 0)
    }
    fn verify_proof_keccak_compressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_100_195_000 picoseconds.
        Weight::from_parts(5_562_679_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 14_493_014_000 picoseconds.
        Weight::from_parts(15_104_943_000, 0)
    }
    fn verify_proof_keccak_uncompressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_470_610_000 picoseconds.
        Weight::from_parts(2_575_822_000, 0)
    }
    fn verify_proof_poseidon_compressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 30_883_223_000 picoseconds.
        Weight::from_parts(31_960_314_000, 0)
    }
    fn verify_proof_keccak_compressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_153_783_000 picoseconds.
        Weight::from_parts(5_320_026_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_700_611_000 picoseconds.
        Weight::from_parts(16_761_738_000, 0)
    }
    fn verify_proof_keccak_uncompressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_611_369_000 picoseconds.
        Weight::from_parts(2_716_382_000, 0)
    }
    fn verify_proof_poseidon_compressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 32_670_654_000 picoseconds.
        Weight::from_parts(34_690_260_000, 0)
    }
    fn verify_proof_keccak_compressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_398_638_000 picoseconds.
        Weight::from_parts(5_609_817_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 16_349_596_000 picoseconds.
        Weight::from_parts(17_196_691_000, 0)
    }
    fn verify_proof_keccak_uncompressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_638_851_000 picoseconds.
        Weight::from_parts(2_762_777_000, 0)
    }
    fn verify_proof_poseidon_compressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 36_651_031_000 picoseconds.
        Weight::from_parts(39_971_727_000, 0)
    }
    fn verify_proof_keccak_compressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_547_402_000 picoseconds.
        Weight::from_parts(7_085_146_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_862_388_000 picoseconds.
        Weight::from_parts(19_453_099_000, 0)
    }
    fn verify_proof_keccak_uncompressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_282_319_000 picoseconds.
        Weight::from_parts(3_400_637_000, 0)
    }
    fn verify_proof_poseidon_compressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 39_493_635_000 picoseconds.
        Weight::from_parts(42_901_016_000, 0)
    }
    fn verify_proof_keccak_compressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_766_962_000 picoseconds.
        Weight::from_parts(7_047_336_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 19_420_479_000 picoseconds.
        Weight::from_parts(20_036_786_000, 0)
    }
    fn verify_proof_keccak_uncompressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_384_819_000 picoseconds.
        Weight::from_parts(3_559_826_000, 0)
    }
    fn verify_proof_poseidon_compressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 40_327_213_000 picoseconds.
        Weight::from_parts(41_923_026_000, 0)
    }
    fn verify_proof_keccak_compressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_057_734_000 picoseconds.
        Weight::from_parts(7_426_084_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 20_195_348_000 picoseconds.
        Weight::from_parts(20_655_751_000, 0)
    }
    fn verify_proof_keccak_uncompressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_440_401_000 picoseconds.
        Weight::from_parts(3_646_847_000, 0)
    }
    fn verify_proof_poseidon_compressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 42_262_056_000 picoseconds.
        Weight::from_parts(45_180_703_000, 0)
    }
    fn verify_proof_keccak_compressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_281_968_000 picoseconds.
        Weight::from_parts(7_674_480_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 21_193_239_000 picoseconds.
        Weight::from_parts(21_523_412_000, 0)
    }
    fn verify_proof_keccak_uncompressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_532_725_000 picoseconds.
        Weight::from_parts(3_617_671_000, 0)
    }
    fn verify_proof_poseidon_compressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 48_580_708_000 picoseconds.
        Weight::from_parts(55_903_578_000, 0)
    }
    fn verify_proof_keccak_compressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_417_026_000 picoseconds.
        Weight::from_parts(8_731_669_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 23_968_631_000 picoseconds.
        Weight::from_parts(27_413_340_000, 0)
    }
    fn verify_proof_keccak_uncompressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 4_245_472_000 picoseconds.
        Weight::from_parts(4_376_777_000, 0)
    }
    fn verify_proof_poseidon_compressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 51_125_165_000 picoseconds.
        Weight::from_parts(54_861_139_000, 0)
    }
    fn verify_proof_keccak_compressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_926_680_000 picoseconds.
        Weight::from_parts(9_363_173_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 25_373_537_000 picoseconds.
        Weight::from_parts(27_237_746_000, 0)
    }
    fn verify_proof_keccak_uncompressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 4_368_392_000 picoseconds.
        Weight::from_parts(4_538_260_000, 0)
    }
}