[relaychain]
default_command = "zkv-relay"
default_args = []
chain = "volta-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1599
chain = "volta-local"
add_to_genesis = true
cumulus_based = true

[[parachains.collators]]
name = "collator-alice"
command = "paratest-node"
args = []

[[parachains.collators]]
name = "collator-bob"
command = "paratest-node"
args = []
