[relaychain]
default_command = "zkv-relay"
default_args = []
chain = "{{CHAIN_NETWORK}}"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1599
chain = "{{CHAIN_NETWORK}}"
add_to_genesis = true
cumulus_based = true

[[parachains.collators]]
name = "collator-alice"
command = "paratest-node"
args = []

[[parachains.collators]]
name = "collator-bob"
command = "paratest-node"
args = []
