[package]
name = "pallet-stwo-verifier"
version = "0.1.0"
description = "A Stwo verifier pallet"
homepage.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "TBD"

[dependencies]
log = "0.4.21"
hex-literal = { version = "0.4.1", optional = true }
codec = { workspace = true }
scale-info = { workspace = true }

hp-verifiers = { workspace = true }
pallet-verifiers = { workspace = true }

frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true, optional = true }
sp-core = { workspace = true }

stwo-verifier = { git = "https://github.com/HorizenLabs/stwo-verifier.git", default-features = false, tag = "v0.1.0" }

[dev-dependencies]
hex-literal = { version = "0.4.1" }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-core/std",
    "frame-support/std",
    "frame-system/std",
    "hp-verifiers/std",
    "pallet-verifiers/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "pallet-verifiers/runtime-benchmarks",
    "dep:hex-literal",
    "dep:sp-runtime",
    "dep:sp-io",
]
