name: Cache and run command inside the container

description: A composite action to run command(s) inside Docker with caching setup if needed.

inputs:
  command:
    description: 'A command to run inside "image_name:image_tag" docker container (e.g., "cargo build -p zkv-relay --release")'
    required: true
    type: string
  use_cache:
    description: 'Whether to use caching: yes or no'
    required: true
    type: string
  cache_key:
    description: 'The cache key name (e.g., "build-relay-paratest")'
    required: false
    type: string
  image_name:
    description: 'Docker image name to use for the command(s) to run in'
    required: false
    type: string
    default: 'zencash/sc-ci-base'
  image_tag:
    description: 'Docker image tag to use for the command(s) to run in'
    required: false
    type: string
    default: 'noble_rust-stable_latest'
  cmake_install:
    description: 'Whether to install CMake'
    required: false
    type: string
    default: ''
  lld_install:
    description: 'Whether to install LLD'
    required: false
    type: string
    default: ''
  cargo_binaries_install:
    description: 'Whether to install extra cargo binaries. Multiple binaries must be comma separated (e.g., "cargo-llvm-cov,cargo-clippy")'
    required: false
    type: string
    default: ''
  nodejs_version_install:
    description: 'Nodejs major version to install. If not provided nodejs is not being installed'
    required: false
    type: string
    default: ''
  skip_wasm_build:
    description: 'If enable disable the runtime wasm build (reduces build time)'
    required: false
    type: string
    default: ''
  try_runtime:
    description: 'If not empty download it with the given version'
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up deps cache if any
      shell: bash
      run: mkdir -p deps

    # Cache restore from repository default branch
    - name: Restore cache
      id: cache_restore
      if: ${{ inputs.use_cache == 'yes' }}
      uses: WarpBuilds/cache/restore@v1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          deps/
        key: ${{ inputs.cache_key }}-${{ github.event.repository.default_branch }}

    - name: Set docker env vars
      shell: bash
      run: |
        echo "USER_ID=$(id -u)" >> "${GITHUB_ENV}"
        echo "GRP_ID=$(id -g)" >> "${GITHUB_ENV}"

    - name: Run Command
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image_name }}
        IMAGE_TAG: ${{ inputs.image_tag }}
        LLD_INSTALL: ${{ inputs.lld_install }}
        CMAKE_INSTALL: ${{ inputs.cmake_install }}
        CARGO_BINARIES_INSTALL: ${{ inputs.cargo_binaries_install }}
        NODEJS_VERSION_INSTALL: ${{ inputs.nodejs_version_install }}
        SKIP_WASM_BUILD: ${{ inputs.skip_wasm_build }}
        TRY_RUNTIME: ${{ inputs.try_runtime }}
        DOCKER_BUILD_DIR: /build
        DOCKER_CARGO_HOME: /tmp/.cargo
      run: |
        docker compose -f ${GITHUB_WORKSPACE}/ci/docker-compose.yml run --rm cargo-container ${{ inputs.command }}

    # Clear cache key for default_branch triggered by merge into default_branch event ONLY
    - name: Clear cache before saving new version
      id: clear_cache
      if: ${{ inputs.use_cache == 'yes' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      uses: WarpBuilds/cache@v1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          deps/
        key: ${{ inputs.cache_key }}-${{ github.event.repository.default_branch }}
        delete-cache: true

    # Save cache key for default_branch triggered by merge into default_branch event ONLY
    - name: Save cache
      if: ${{ inputs.use_cache == 'yes' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && steps.clear_cache.outcome == 'success' }}
      uses: WarpBuilds/cache/save@v1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          deps/
        key: ${{ inputs.cache_key }}-${{ github.event.repository.default_branch }}
