[package]
name = "polkadot-parachain-lib"
version = "0.3.0"
description = "This is NOT the real polkadot-parachain-lib! This is a fake empty package to break circular dependency caused by indirect dependencies on polkadot-sdk umbrella crate."

[features]
std = []
try-runtime = []
runtime-benchmarks = []

