// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_kimchi_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-06-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ozans-MacBook-Pro`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`
//!
//! Kimchi verification uses benchmark-informed formula weights. The domain base
//! tiers below come from benchmark measurements with guard margins; the
//! public-input coefficient is derived from `#[benchmark(extra)]` scaling probes
//! and rounded up for the production formula.

// Executed Command:
// ./target/release/zkv-relay
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-kimchi-verifier-verify-proof
// --extrinsic
// verify_proof_domain_4096
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// ./HEADER-APACHE2
// --template
// ./relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --output
// ./runtime/zkverify/src/weights/pallet_kimchi_verifier_verify_proof.rs
// --base-path
// /tmp/zkv-kimchi-native-srs-4096

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_kimchi_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_kimchi_verifier_verify_proof::WeightInfo for ZKVWeight<T> {
    fn verify_proof_domain_4096_pubs_0() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Measured median execution time: 15_993_000_000 picoseconds.
        // Includes guard margin over a small simple-profile benchmark. Feature-heavy
        // small proofs route to the one-chunk upper tier.
        Weight::from_parts(21_000_000_000, 0)
    }

    fn verify_proof_domain_65536_pubs_0() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Measured median execution time: 62_396_000_000 picoseconds.
        // Includes guard margin over the max-feature one-chunk benchmark.
        Weight::from_parts(80_000_000_000, 0)
    }

    fn verify_proof_domain_131072_pubs_0() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Measured median execution time: 81_968_000_000 picoseconds.
        // Includes guard margin over the two-chunk lookup/runtime-table profile benchmark.
        Weight::from_parts(105_000_000_000, 0)
    }

    fn verify_proof_domain_262144_pubs_0() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Measured median execution time: 139_340_000_000 picoseconds.
        // Includes guard margin over the four-chunk lookup/runtime-table profile benchmark.
        Weight::from_parts(176_000_000_000, 0)
    }

    fn verify_proof_public_input() -> Weight {
        // Per-public-input, per-chunk slope.
        // Local benchmark slopes are about 7.5 us/chunk/public input, rounded
        // up to 10 us for the production formula.
        Weight::from_parts(10_000_000, 0)
    }
}
