// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_staking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `2dddecaab93f`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_staking.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.yy4bwRyPb4

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_staking` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_staking::WeightInfo for ZKVWeight<T> {
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn bond() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `989`
        //  Estimated: `4339`
        // Minimum execution time: 73_577_000 picoseconds.
        Weight::from_parts(75_411_000, 4339)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    fn bond_extra() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1837`
        //  Estimated: `8877`
        // Minimum execution time: 128_890_000 picoseconds.
        Weight::from_parts(130_242_000, 8877)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:0)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    fn unbond() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2042`
        //  Estimated: `8877`
        // Minimum execution time: 106_739_000 picoseconds.
        Weight::from_parts(107_661_000, 8877)
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_update(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1058`
        //  Estimated: `4339`
        // Minimum execution time: 66_775_000 picoseconds.
        Weight::from_parts(68_179_691, 4339)
            // Standard Error: 1_158
            .saturating_add(Weight::from_parts(32_456, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:1)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_kill(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2043 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 115_966_000 picoseconds.
        Weight::from_parts(121_143_694, 6248)
            // Standard Error: 2_284
            .saturating_add(Weight::from_parts(1_519_736, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(14_u64))
            .saturating_add(T::DbWeight::get().writes(12_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:1 w:0)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinCommission` (r:1 w:0)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:1)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:1 w:1)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForValidators` (r:1 w:1)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn validate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1271`
        //  Estimated: `4339`
        // Minimum execution time: 60_303_000 picoseconds.
        Weight::from_parts(61_474_000, 4339)
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:128 w:128)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// The range of component `k` is `[1, 128]`.
    fn kick(k: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1887 + k * (379 ±0)`
        //  Estimated: `4339 + k * (2841 ±0)`
        // Minimum execution time: 31_839_000 picoseconds.
        Weight::from_parts(32_057_346, 4339)
            // Standard Error: 3_754
            .saturating_add(Weight::from_parts(6_733_392, 0).saturating_mul(k.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(k.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
            .saturating_add(Weight::from_parts(0, 2841).saturating_mul(k.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:11 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 10]`.
    fn nominate(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1809 + n * (96 ±0)`
        //  Estimated: `6248 + n * (2520 ±0)`
        // Minimum execution time: 75_931_000 picoseconds.
        Weight::from_parts(73_544_849, 6248)
            // Standard Error: 19_016
            .saturating_add(Weight::from_parts(4_544_878, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(6_u64))
            .saturating_add(Weight::from_parts(0, 2520).saturating_mul(n.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn chill() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1703`
        //  Estimated: `6248`
        // Minimum execution time: 65_412_000 picoseconds.
        Weight::from_parts(66_173_000, 6248)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn set_payee() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `854`
        //  Estimated: `4339`
        // Minimum execution time: 23_523_000 picoseconds.
        Weight::from_parts(23_975_000, 4339)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:1 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn update_payee() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `921`
        //  Estimated: `4339`
        // Minimum execution time: 26_930_000 picoseconds.
        Weight::from_parts(27_962_000, 4339)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:2 w:2)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    fn set_controller() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `854`
        //  Estimated: `7688`
        // Minimum execution time: 27_200_000 picoseconds.
        Weight::from_parts(27_571_000, 7688)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Staking::ValidatorCount` (r:0 w:1)
    /// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_validator_count() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_054_000 picoseconds.
        Weight::from_parts(2_284_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_no_eras() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_022_000 picoseconds.
        Weight::from_parts(6_452_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_new_era() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_981_000 picoseconds.
        Weight::from_parts(6_252_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::ForceEra` (r:0 w:1)
    /// Proof: `Staking::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    fn force_new_era_always() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_041_000 picoseconds.
        Weight::from_parts(6_432_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Invulnerables` (r:0 w:1)
    /// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// The range of component `v` is `[0, 200]`.
    fn set_invulnerables(v: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_164_000 picoseconds.
        Weight::from_parts(2_512_714, 0)
            // Standard Error: 77
            .saturating_add(Weight::from_parts(8_969, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Ledger` (r:2 w:2)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:1 w:0)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// The range of component `u` is `[0, 1]`.
    fn deprecate_controller_batch(u: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + u * (921 ±0)`
        //  Estimated: `3844 + u * (3844 ±0)`
        // Minimum execution time: 3_808_000 picoseconds.
        Weight::from_parts(4_208_102, 3844)
            // Standard Error: 19_617
            .saturating_add(Weight::from_parts(30_706_797, 0).saturating_mul(u.into()))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(u.into())))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(u.into())))
            .saturating_add(Weight::from_parts(0, 3844).saturating_mul(u.into()))
    }
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:1)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[0, 100]`.
    fn force_unstake(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2043 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 110_646_000 picoseconds.
        Weight::from_parts(116_708_398, 6248)
            // Standard Error: 2_547
            .saturating_add(Weight::from_parts(1_463_472, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(14_u64))
            .saturating_add(T::DbWeight::get().writes(13_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `Staking::UnappliedSlashes` (r:1 w:1)
    /// Proof: `Staking::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `s` is `[1, 1000]`.
    fn cancel_deferred_slash(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `66626`
        //  Estimated: `70091`
        // Minimum execution time: 124_181_000 picoseconds.
        Weight::from_parts(900_147_483, 70091)
            // Standard Error: 55_900
            .saturating_add(Weight::from_parts(4_732_812, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Bonded` (r:65 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:65 w:65)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersClipped` (r:1 w:0)
    /// Proof: `Staking::ErasStakersClipped` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasStakersOverview` (r:1 w:0)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ClaimedRewards` (r:1 w:1)
    /// Proof: `Staking::ClaimedRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasValidatorReward` (r:1 w:0)
    /// Proof: `Staking::ErasValidatorReward` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:65 w:65)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:65 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:65 w:65)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersPaged` (r:1 w:0)
    /// Proof: `Staking::ErasStakersPaged` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasRewardPoints` (r:1 w:0)
    /// Proof: `Staking::ErasRewardPoints` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasValidatorPrefs` (r:1 w:0)
    /// Proof: `Staking::ErasValidatorPrefs` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:65 w:0)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 64]`.
    fn payout_stakers_alive_staked(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `8134 + n * (392 ±0)`
        //  Estimated: `10703 + n * (3349 ±3)`
        // Minimum execution time: 185_104_000 picoseconds.
        Weight::from_parts(211_261_566, 10703)
            // Standard Error: 160_629
            .saturating_add(Weight::from_parts(81_855_108, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(14_u64))
            .saturating_add(T::DbWeight::get().reads((6_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(n.into()))
    }
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:0)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:3 w:3)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:2 w:2)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// The range of component `l` is `[1, 32]`.
    fn rebond(l: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1838 + l * (7 ±0)`
        //  Estimated: `8877`
        // Minimum execution time: 85_389_000 picoseconds.
        Weight::from_parts(87_095_692, 8877)
            // Standard Error: 2_306
            .saturating_add(Weight::from_parts(57_236, 0).saturating_mul(l.into()))
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::VirtualStakers` (r:1 w:1)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashingSpans` (r:1 w:1)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:0 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SpanSlash` (r:0 w:100)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// The range of component `s` is `[1, 100]`.
    fn reap_stash(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2043 + s * (4 ±0)`
        //  Estimated: `6248 + s * (4 ±0)`
        // Minimum execution time: 125_954_000 picoseconds.
        Weight::from_parts(126_552_041, 6248)
            // Standard Error: 2_394
            .saturating_add(Weight::from_parts(1_462_701, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(12_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
            .saturating_add(Weight::from_parts(0, 4).saturating_mul(s.into()))
    }
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:0)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:155 w:0)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:110 w:0)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:110 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:110 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:110 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:11 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForValidators` (r:1 w:0)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ValidatorCount` (r:1 w:0)
    /// Proof: `Staking::ValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumValidatorCount` (r:1 w:0)
    /// Proof: `Staking::MinimumValidatorCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CurrentEra` (r:1 w:1)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasValidatorPrefs` (r:0 w:10)
    /// Proof: `Staking::ErasValidatorPrefs` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersPaged` (r:0 w:20)
    /// Proof: `Staking::ErasStakersPaged` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasStakersOverview` (r:0 w:10)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasTotalStake` (r:0 w:1)
    /// Proof: `Staking::ErasTotalStake` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStartSessionIndex` (r:0 w:1)
    /// Proof: `Staking::ErasStartSessionIndex` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumActiveStake` (r:0 w:1)
    /// Proof: `Staking::MinimumActiveStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    fn new_era(v: u32, n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + n * (718 ±0) + v * (3596 ±0)`
        //  Estimated: `397325 + n * (3349 ±0) + v * (3349 ±0)`
        // Minimum execution time: 610_337_000 picoseconds.
        Weight::from_parts(613_984_000, 397325)
            // Standard Error: 1_766_543
            .saturating_add(Weight::from_parts(60_526_884, 0).saturating_mul(v.into()))
            // Standard Error: 176_026
            .saturating_add(Weight::from_parts(20_465_936, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(161_u64))
            .saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(8_u64))
            .saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(v.into())))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(v.into()))
    }
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:0)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:155 w:0)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:5200 w:0)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:5200 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:5200 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:5200 w:0)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:200 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinimumActiveStake` (r:0 w:1)
    /// Proof: `Staking::MinimumActiveStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[100, 200]`.
    /// The range of component `n` is `[2500, 5000]`.
    fn get_npos_voters(v: u32, n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1416 + n * (717 ±0) + v * (393 ±0)`
        //  Estimated: `397325 + n * (3349 ±0) + v * (3349 ±0)`
        // Minimum execution time: 67_138_022_000 picoseconds.
        Weight::from_parts(67_461_738_000, 397325)
            // Standard Error: 155_636
            .saturating_add(Weight::from_parts(21_577_525, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(156_u64))
            .saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(v.into())))
            .saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(n.into()))
            .saturating_add(Weight::from_parts(0, 3349).saturating_mul(v.into()))
    }
    /// Storage: `Staking::CounterForValidators` (r:1 w:0)
    /// Proof: `Staking::CounterForValidators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:201 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// The range of component `v` is `[100, 200]`.
    fn get_npos_targets(v: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `602 + v * (50 ±0)`
        //  Estimated: `3510 + v * (2520 ±0)`
        // Minimum execution time: 605_459_000 picoseconds.
        Weight::from_parts(29_148_841, 3510)
            // Standard Error: 13_105
            .saturating_add(Weight::from_parts(5_882_044, 0).saturating_mul(v.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(v.into())))
            .saturating_add(Weight::from_parts(0, 2520).saturating_mul(v.into()))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:0 w:1)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxStakedRewards` (r:0 w:1)
    /// Proof: `Staking::MaxStakedRewards` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:0 w:1)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:0 w:1)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_staking_configs_all_set() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_346_000 picoseconds.
        Weight::from_parts(3_546_000, 0)
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinValidatorBond` (r:0 w:1)
    /// Proof: `Staking::MinValidatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxValidatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxValidatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxStakedRewards` (r:0 w:1)
    /// Proof: `Staking::MaxStakedRewards` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:0 w:1)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:0 w:1)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:0 w:1)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_staking_configs_all_remove() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_326_000 picoseconds.
        Weight::from_parts(3_416_000, 0)
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Nominators` (r:1 w:1)
    /// Proof: `Staking::Nominators` (`max_values`: None, `max_size`: Some(366), added: 2841, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ChillThreshold` (r:1 w:0)
    /// Proof: `Staking::ChillThreshold` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MaxNominatorsCount` (r:1 w:0)
    /// Proof: `Staking::MaxNominatorsCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::CounterForNominators` (r:1 w:1)
    /// Proof: `Staking::CounterForNominators` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::MinNominatorBond` (r:1 w:0)
    /// Proof: `Staking::MinNominatorBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:0)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::Lock` (r:1 w:0)
    /// Proof: `VoterList::Lock` (`max_values`: Some(1), `max_size`: Some(0), added: 495, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListNodes` (r:2 w:2)
    /// Proof: `VoterList::ListNodes` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::ListBags` (r:1 w:1)
    /// Proof: `VoterList::ListBags` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
    /// Storage: `VoterList::CounterForListNodes` (r:1 w:1)
    /// Proof: `VoterList::CounterForListNodes` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn chill_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1839`
        //  Estimated: `6248`
        // Minimum execution time: 78_586_000 picoseconds.
        Weight::from_parts(79_498_000, 6248)
            .saturating_add(T::DbWeight::get().reads(13_u64))
            .saturating_add(T::DbWeight::get().writes(6_u64))
    }
    /// Storage: `Staking::MinCommission` (r:1 w:0)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Validators` (r:1 w:1)
    /// Proof: `Staking::Validators` (`max_values`: None, `max_size`: Some(45), added: 2520, mode: `MaxEncodedLen`)
    fn force_apply_min_commission() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `644`
        //  Estimated: `3510`
        // Minimum execution time: 14_307_000 picoseconds.
        Weight::from_parts(14_657_000, 3510)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::MinCommission` (r:0 w:1)
    /// Proof: `Staking::MinCommission` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_min_commission() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_954_000 picoseconds.
        Weight::from_parts(2_124_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `System::Account` (r:1 w:0)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:0)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    fn restore_ledger() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `994`
        //  Estimated: `4339`
        // Minimum execution time: 45_414_000 picoseconds.
        Weight::from_parts(46_597_000, 4339)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(185), added: 2660, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(874), added: 3349, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
    fn migrate_currency() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1165`
        //  Estimated: `4764`
        // Minimum execution time: 96_029_000 picoseconds.
        Weight::from_parts(97_131_000, 4764)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStartSessionIndex` (r:1 w:0)
    /// Proof: `Staking::ErasStartSessionIndex` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashRewardFraction` (r:1 w:0)
    /// Proof: `Staking::SlashRewardFraction` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ActiveEra` (r:1 w:0)
    /// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Invulnerables` (r:1 w:0)
    /// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ErasStakersOverview` (r:1 w:0)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersPaged` (r:1 w:0)
    /// Proof: `Staking::ErasStakersPaged` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Session::DisabledValidators` (r:1 w:0)
    /// Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Session::Validators` (r:1 w:0)
    /// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ValidatorSlashInEra` (r:1 w:1)
    /// Proof: `Staking::ValidatorSlashInEra` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::SlashingSpans` (r:65 w:65)
    /// Proof: `Staking::SlashingSpans` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::SpanSlash` (r:65 w:65)
    /// Proof: `Staking::SpanSlash` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
    /// Storage: `Staking::NominatorSlashInEra` (r:64 w:64)
    /// Proof: `Staking::NominatorSlashInEra` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
    /// Storage: `Staking::UnappliedSlashes` (r:1 w:1)
    /// Proof: `Staking::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn manual_slash() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `3719`
        //  Estimated: `166805`
        // Minimum execution time: 960_117_000 picoseconds.
        Weight::from_parts(967_160_000, 166805)
            .saturating_add(T::DbWeight::get().reads(205_u64))
            .saturating_add(T::DbWeight::get().writes(196_u64))
    }
}
