// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_ultrahonk_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192bf73bcbe1`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-ultrahonk-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_ultrahonk_verifier_verify_proof.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.hDt6KMqdsD

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_ultrahonk_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_ultrahonk_verifier_verify_proof::WeightInfo for ZKVWeight<T> {
    fn verify_proof_zk_32() -> Weight {
        // TODO: Replace with actual benchmarked weights for V0_84
        Weight::from_parts(3_000_000_000, 0)
    }
    fn verify_proof_plain_32() -> Weight {
        // TODO: Replace with actual benchmarked weights for V0_84
        Weight::from_parts(2_800_000_000, 0)
    }
    fn verify_zk_proof_log_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_923_392_000 picoseconds.
        Weight::from_parts(2_958_869_000, 0)
    }
    fn verify_plain_proof_log_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_693_173_000 picoseconds.
        Weight::from_parts(2_714_272_000, 0)
    }
    fn verify_zk_proof_log_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_969_588_000 picoseconds.
        Weight::from_parts(2_988_433_000, 0)
    }
    fn verify_plain_proof_log_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_732_246_000 picoseconds.
        Weight::from_parts(2_747_874_000, 0)
    }
    fn verify_zk_proof_log_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_966_823_000 picoseconds.
        Weight::from_parts(3_025_243_000, 0)
    }
    fn verify_plain_proof_log_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_758_294_000 picoseconds.
        Weight::from_parts(2_785_505_000, 0)
    }
    fn verify_zk_proof_log_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_024_581_000 picoseconds.
        Weight::from_parts(3_056_690_000, 0)
    }
    fn verify_plain_proof_log_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_782_109_000 picoseconds.
        Weight::from_parts(2_820_690_000, 0)
    }
    fn verify_zk_proof_log_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_072_590_000 picoseconds.
        Weight::from_parts(3_102_035_000, 0)
    }
    fn verify_plain_proof_log_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_840_989_000 picoseconds.
        Weight::from_parts(2_856_698_000, 0)
    }
    fn verify_zk_proof_log_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_115_480_000 picoseconds.
        Weight::from_parts(3_142_872_000, 0)
    }
    fn verify_plain_proof_log_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_865_133_000 picoseconds.
        Weight::from_parts(2_892_725_000, 0)
    }
    fn verify_zk_proof_log_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_146_829_000 picoseconds.
        Weight::from_parts(3_195_800_000, 0)
    }
    fn verify_plain_proof_log_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_894_177_000 picoseconds.
        Weight::from_parts(2_919_745_000, 0)
    }
    fn verify_zk_proof_log_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_202_141_000 picoseconds.
        Weight::from_parts(3_223_893_000, 0)
    }
    fn verify_plain_proof_log_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_933_722_000 picoseconds.
        Weight::from_parts(2_955_773_000, 0)
    }
    fn verify_zk_proof_log_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_200_519_000 picoseconds.
        Weight::from_parts(3_231_467_000, 0)
    }
    fn verify_plain_proof_log_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_921_699_000 picoseconds.
        Weight::from_parts(2_951_114_000, 0)
    }
    fn verify_zk_proof_log_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_248_158_000 picoseconds.
        Weight::from_parts(3_286_639_000, 0)
    }
    fn verify_plain_proof_log_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_960_040_000 picoseconds.
        Weight::from_parts(2_991_119_000, 0)
    }
    fn verify_zk_proof_log_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_287_852_000 picoseconds.
        Weight::from_parts(3_320_142_000, 0)
    }
    fn verify_plain_proof_log_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_031_213_000 picoseconds.
        Weight::from_parts(3_062_422_000, 0)
    }
    fn verify_zk_proof_log_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_315_102_000 picoseconds.
        Weight::from_parts(3_359_746_000, 0)
    }
    fn verify_plain_proof_log_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_063_022_000 picoseconds.
        Weight::from_parts(3_093_660_000, 0)
    }
    fn verify_zk_proof_log_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_359_836_000 picoseconds.
        Weight::from_parts(3_375_986_000, 0)
    }
    fn verify_plain_proof_log_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_090_985_000 picoseconds.
        Weight::from_parts(3_114_218_000, 0)
    }
    fn verify_zk_proof_log_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_393_580_000 picoseconds.
        Weight::from_parts(3_434_505_000, 0)
    }
    fn verify_plain_proof_log_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_121_061_000 picoseconds.
        Weight::from_parts(3_174_080_000, 0)
    }
    fn verify_zk_proof_log_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_435_237_000 picoseconds.
        Weight::from_parts(3_467_848_000, 0)
    }
    fn verify_plain_proof_log_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_160_173_000 picoseconds.
        Weight::from_parts(3_187_554_000, 0)
    }
    fn verify_zk_proof_log_22() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_483_717_000 picoseconds.
        Weight::from_parts(3_517_389_000, 0)
    }
    fn verify_plain_proof_log_22() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_205_358_000 picoseconds.
        Weight::from_parts(3_240_573_000, 0)
    }
    fn verify_zk_proof_log_23() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_502_292_000 picoseconds.
        Weight::from_parts(3_533_891_000, 0)
    }
    fn verify_plain_proof_log_23() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_205_518_000 picoseconds.
        Weight::from_parts(3_243_609_000, 0)
    }
    fn verify_zk_proof_log_24() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_552_005_000 picoseconds.
        Weight::from_parts(3_591_759_000, 0)
    }
    fn verify_plain_proof_log_24() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_256_914_000 picoseconds.
        Weight::from_parts(3_290_917_000, 0)
    }
    fn verify_zk_proof_log_25() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_569_467_000 picoseconds.
        Weight::from_parts(3_603_841_000, 0)
    }
    fn verify_plain_proof_log_25() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_286_480_000 picoseconds.
        Weight::from_parts(3_325_161_000, 0)
    }
}