// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_token_claim`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-02-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `b937794847f4`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-token-claim
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_token_claim.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.yy4bwRyPb4

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_token_claim` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_token_claim::WeightInfo for ZKVWeight<T> {
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:0)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:1)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::ClaimId` (r:1 w:1)
    /// Proof: `TokenClaim::ClaimId` (`max_values`: Some(1), `max_size`: Some(510), added: 1005, mode: `MaxEncodedLen`)
    fn begin_claim() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `42`
        //  Estimated: `1995`
        // Minimum execution time: 11_020_000 picoseconds.
        Weight::from_parts(11_331_000, 1995)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::ClaimId` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimId` (`max_values`: Some(1), `max_size`: Some(510), added: 1005, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:1 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn claim() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2363`
        //  Estimated: `6196`
        // Minimum execution time: 263_781_000 picoseconds.
        Weight::from_parts(266_266_000, 6196)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::ClaimId` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimId` (`max_values`: Some(1), `max_size`: Some(510), added: 1005, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:1 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn claim_ethereum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2368`
        //  Estimated: `6196`
        // Minimum execution time: 219_960_000 picoseconds.
        Weight::from_parts(224_298_000, 6196)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:1 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn claim_for() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1859`
        //  Estimated: `6196`
        // Minimum execution time: 80_400_000 picoseconds.
        Weight::from_parts(81_782_000, 6196)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:1 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn claim_ethereum_for() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1869`
        //  Estimated: `6196`
        // Minimum execution time: 82_674_000 picoseconds.
        Weight::from_parts(84_327_000, 6196)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:0)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:1 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:10000 w:10000)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 10000]`.
    fn add_beneficiaries(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `253`
        //  Estimated: `3593 + n * (2532 ±0)`
        // Minimum execution time: 20_038_000 picoseconds.
        Weight::from_parts(20_758_000, 3593)
            // Standard Error: 3_357
            .saturating_add(Weight::from_parts(6_048_402, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2532).saturating_mul(n.into()))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:1)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::PalletAccountId` (r:1 w:0)
    /// Proof: `TokenClaim::PalletAccountId` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::ClaimId` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimId` (`max_values`: Some(1), `max_size`: Some(510), added: 1005, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::TotalClaimable` (r:0 w:1)
    /// Proof: `TokenClaim::TotalClaimable` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn end_claim() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `853`
        //  Estimated: `6196`
        // Minimum execution time: 52_078_000 picoseconds.
        Weight::from_parts(53_059_000, 6196)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `TokenClaim::ClaimActive` (r:1 w:0)
    /// Proof: `TokenClaim::ClaimActive` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::CounterForBeneficiaries` (r:1 w:1)
    /// Proof: `TokenClaim::CounterForBeneficiaries` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `TokenClaim::Beneficiaries` (r:10000 w:10000)
    /// Proof: `TokenClaim::Beneficiaries` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 10000]`.
    fn remove_beneficiaries(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `614 + n * (55 ±0)`
        //  Estimated: `1489 + n * (2532 ±0)`
        // Minimum execution time: 12_984_000 picoseconds.
        Weight::from_parts(13_385_000, 1489)
            // Standard Error: 1_955
            .saturating_add(Weight::from_parts(1_402_184, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
            .saturating_add(Weight::from_parts(0, 2532).saturating_mul(n.into()))
    }
}
