// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_ultrahonk_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-02-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192bf73bcbe1`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-ultrahonk-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_ultrahonk_verifier_verify_proof.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.hDt6KMqdsD

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_ultrahonk_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_ultrahonk_verifier_verify_proof::WeightInfo for ZKVWeight<T> {

    fn verify_zk_proof_v0_84() -> Weight {
        // TODO: Replace with actual benchmark results for V0.84 with 32 public inputs
        Weight::from_parts(12_042_713_000, 0)
    }
    fn verify_plain_proof_v0_84() -> Weight {
        // TODO: Replace with actual benchmark results for V0.84 with 32 public inputs
        Weight::from_parts(10_641_276_000, 0)
    }

    fn verify_zk_proof_v3_0(log_n: u64, ) -> Weight {
        // PLACEHOLDER VALUE
        Weight::from_parts(3_674_034_551, 0)
            .saturating_add(Weight::from_parts(204_571_428, 0).saturating_mul(log_n.into()))
    }
    
    fn verify_plain_proof_v3_0(log_n: u64, ) -> Weight {
        // PLACEHOLDER VALUE
        Weight::from_parts(3_674_034_551, 0)
            .saturating_add(Weight::from_parts(204_571_428, 0).saturating_mul(log_n.into()))
    }
}