// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_crl`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-03-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `6437633dd8b4`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-crl
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_crl.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.OdhuN4pq6R

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_crl` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_crl::WeightInfo for ZKVWeight<T> {
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2537), added: 5012, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(2910084), added: 2912559, mode: `MaxEncodedLen`)
    fn register_ca() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `6002`
        // Minimum execution time: 15_319_000 picoseconds.
        Weight::from_parts(16_171_000, 6002)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2537), added: 5012, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(2910084), added: 2912559, mode: `MaxEncodedLen`)
    fn unregister_ca() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `557`
        //  Estimated: `6002`
        // Minimum execution time: 16_551_000 picoseconds.
        Weight::from_parts(17_242_000, 6002)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2537), added: 5012, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:1 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(2910084), added: 2912559, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 1000]`.
    fn update_pem_crl(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `614`
        //  Estimated: `2913549`
        // Minimum execution time: 4_360_308_000 picoseconds.
        Weight::from_parts(4_309_597_256, 2913549)
            // Standard Error: 23_700
            .saturating_add(Weight::from_parts(1_384_762, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2537), added: 5012, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:1 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(2910084), added: 2912559, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 1000]`.
    fn update_der_crl(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `614`
        //  Estimated: `2913549`
        // Minimum execution time: 4_332_024_000 picoseconds.
        Weight::from_parts(4_296_036_500, 2913549)
            // Standard Error: 19_298
            .saturating_add(Weight::from_parts(1_113_783, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(2910084), added: 2912559, mode: `MaxEncodedLen`)
    fn clear_crl() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_292_000 picoseconds.
        Weight::from_parts(1_372_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}
