// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_tee_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-01-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `95a754ce88e4`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-tee-verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/zkverify/src/weights/pallet_tee_verifier.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.zcaNfVv78Z

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_tee_verifier` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_tee_verifier::WeightInfo for ZKVWeight<T> {
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn verify_proof() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `57`
        //  Estimated: `1493`
        // Minimum execution time: 7_347_520_000 picoseconds.
        Weight::from_parts(7_364_282_000, 1493)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `SettlementTeePallet::Vks` (r:1 w:0)
    /// Proof: `SettlementTeePallet::Vks` (`max_values`: None, `max_size`: Some(16428), added: 18903, mode: `MaxEncodedLen`)
    fn get_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6394`
        //  Estimated: `19893`
        // Minimum execution time: 7_734_000 picoseconds.
        Weight::from_parts(7_925_000, 19893)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn validate_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `57`
        //  Estimated: `1493`
        // Minimum execution time: 4_630_208_000 picoseconds.
        Weight::from_parts(4_640_277_000, 1493)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
    fn compute_statement_hash() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 20_188_000 picoseconds.
        Weight::from_parts(20_318_000, 0)
    }
    /// Storage: `SettlementTeePallet::Disabled` (r:1 w:0)
    /// Proof: `SettlementTeePallet::Disabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `SettlementTeePallet::Tickets` (r:1 w:1)
    /// Proof: `SettlementTeePallet::Tickets` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
    /// Storage: `SettlementTeePallet::Vks` (r:1 w:1)
    /// Proof: `SettlementTeePallet::Vks` (`max_values`: None, `max_size`: Some(16428), added: 18903, mode: `MaxEncodedLen`)
    fn register_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `171`
        //  Estimated: `19893`
        // Minimum execution time: 4_551_652_000 picoseconds.
        Weight::from_parts(4_562_302_000, 19893)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `SettlementTeePallet::Tickets` (r:1 w:1)
    /// Proof: `SettlementTeePallet::Tickets` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(157), added: 2632, mode: `MaxEncodedLen`)
    /// Storage: `SettlementTeePallet::Vks` (r:1 w:1)
    /// Proof: `SettlementTeePallet::Vks` (`max_values`: None, `max_size`: Some(16428), added: 18903, mode: `MaxEncodedLen`)
    fn unregister_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6559`
        //  Estimated: `19893`
        // Minimum execution time: 39_994_000 picoseconds.
        Weight::from_parts(40_886_000, 19893)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}
