// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_plonky2_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-06-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `582e8ea9a91b`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-plonky2-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/src/weights/pallet_plonky2_verifier_verify_proof.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.VMRZkLxJb9

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;
use crate::weight_aliases::*;

/// Weights for `pallet_plonky2_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_plonky2_verifier_verify_proof::WeightInfo for ZKVWeight<T> {
    fn verify_proof_poseidon_uncompressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 9_846_062_000 picoseconds.
        Weight::from_parts(9_860_419_000, 0)
    }
    fn verify_proof_keccak_uncompressed_2() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_243_850_000 picoseconds.
        Weight::from_parts(1_251_404_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 10_781_279_000 picoseconds.
        Weight::from_parts(10_795_646_000, 0)
    }
    fn verify_proof_keccak_uncompressed_3() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_333_809_000 picoseconds.
        Weight::from_parts(1_339_601_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 11_743_086_000 picoseconds.
        Weight::from_parts(11_755_710_000, 0)
    }
    fn verify_proof_keccak_uncompressed_4() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_413_631_000 picoseconds.
        Weight::from_parts(1_420_413_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_723_468_000 picoseconds.
        Weight::from_parts(12_753_014_000, 0)
    }
    fn verify_proof_keccak_uncompressed_5() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 1_515_883_000 picoseconds.
        Weight::from_parts(1_520_963_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_619_509_000 picoseconds.
        Weight::from_parts(15_641_600_000, 0)
    }
    fn verify_proof_keccak_uncompressed_6() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_461_401_000 picoseconds.
        Weight::from_parts(2_472_341_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 16_797_203_000 picoseconds.
        Weight::from_parts(16_826_799_000, 0)
    }
    fn verify_proof_keccak_uncompressed_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_560_869_000 picoseconds.
        Weight::from_parts(2_572_299_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 17_982_131_000 picoseconds.
        Weight::from_parts(18_028_359_000, 0)
    }
    fn verify_proof_keccak_uncompressed_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_670_225_000 picoseconds.
        Weight::from_parts(2_678_580_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 19_311_873_000 picoseconds.
        Weight::from_parts(19_336_289_000, 0)
    }
    fn verify_proof_keccak_uncompressed_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_787_396_000 picoseconds.
        Weight::from_parts(2_792_486_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 22_334_722_000 picoseconds.
        Weight::from_parts(22_359_338_000, 0)
    }
    fn verify_proof_keccak_uncompressed_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_748_701_000 picoseconds.
        Weight::from_parts(3_762_507_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 23_741_228_000 picoseconds.
        Weight::from_parts(23_798_397_000, 0)
    }
    fn verify_proof_keccak_uncompressed_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_876_843_000 picoseconds.
        Weight::from_parts(3_887_093_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 25_163_023_000 picoseconds.
        Weight::from_parts(25_203_640_000, 0)
    }
    fn verify_proof_keccak_uncompressed_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 3_996_740_000 picoseconds.
        Weight::from_parts(4_012_961_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 26_609_925_000 picoseconds.
        Weight::from_parts(26_634_852_000, 0)
    }
    fn verify_proof_keccak_uncompressed_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 4_140_071_000 picoseconds.
        Weight::from_parts(4_158_666_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 30_002_022_000 picoseconds.
        Weight::from_parts(30_038_299_000, 0)
    }
    fn verify_proof_keccak_uncompressed_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_179_644_000 picoseconds.
        Weight::from_parts(5_194_673_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 31_636_467_000 picoseconds.
        Weight::from_parts(31_671_654_000, 0)
    }
    fn verify_proof_keccak_uncompressed_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_248_614_000 picoseconds.
        Weight::from_parts(5_259_996_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 33_334_482_000 picoseconds.
        Weight::from_parts(33_377_224_000, 0)
    }
    fn verify_proof_keccak_uncompressed_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_394_489_000 picoseconds.
        Weight::from_parts(5_408_976_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 34_973_647_000 picoseconds.
        Weight::from_parts(35_029_923_000, 0)
    }
    fn verify_proof_keccak_uncompressed_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_545_083_000 picoseconds.
        Weight::from_parts(5_570_341_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 38_898_657_000 picoseconds.
        Weight::from_parts(38_931_089_000, 0)
    }
    fn verify_proof_keccak_uncompressed_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_570_950_000 picoseconds.
        Weight::from_parts(6_577_694_000, 0)
    }
    fn verify_proof_poseidon_uncompressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 40_700_939_000 picoseconds.
        Weight::from_parts(40_754_259_000, 0)
    }
    fn verify_proof_keccak_uncompressed_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_731_053_000 picoseconds.
        Weight::from_parts(6_739_268_000, 0)
    }
}
