// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_kimchi_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-06-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ozans-MacBook-Pro`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/zkv-relay
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-kimchi-verifier-verify-proof
// --extrinsic
// verify_proof_domain_4096
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// ./HEADER-APACHE2
// --template
// ./relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --output
// ./runtime/zkverify/src/weights/pallet_kimchi_verifier_verify_proof.rs
// --base-path
// /tmp/zkv-kimchi-native-srs-4096

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use crate::weight_aliases::*;
use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;

/// Weights for `pallet_kimchi_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_kimchi_verifier_verify_proof::WeightInfo for ZKVWeight<T> {
    fn verify_proof_domain_4096() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 15_495_000_000 picoseconds.
        // Includes a 25% margin over the strict Vesta16 profile benchmark.
        Weight::from_parts(19_798_000_000, 0)
    }

    fn verify_proof_domain_65536_pubs_64() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 56_800_000_000 picoseconds.
        // Includes a 25% margin over the strict Vesta16 profile benchmark.
        Weight::from_parts(74_082_000_000, 0)
    }
}
