// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_risc0_verifier_tuning`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-02-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `miklap`, CPU: `11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/zkv-node
// benchmark
// pallet
// --runtime
// ./target/release/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet_risc0_verifier_tuning
// --extrinsic
// *
// --header
// HEADER-APACHE2
// --output
// verifiers/risc0/src/weight_verify_proof
// --template
// node/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_risc0_verifier_tuning`.
pub trait WeightInfo {
    fn verify_proof_succinct() -> Weight;
    fn verify_proof_segment_poseidon2_16() -> Weight;
    fn verify_proof_segment_sha_256_16() -> Weight;
    fn verify_proof_segment_poseidon2_17() -> Weight;
    fn verify_proof_segment_sha_256_17() -> Weight;
    fn verify_proof_segment_poseidon2_18() -> Weight;
    fn verify_proof_segment_sha_256_18() -> Weight;
    fn verify_proof_segment_poseidon2_19() -> Weight;
    fn verify_proof_segment_sha_256_19() -> Weight;
    fn verify_proof_segment_poseidon2_20() -> Weight;
    fn verify_proof_segment_sha_256_20() -> Weight;
    fn verify_proof_segment_poseidon2_21() -> Weight;
    fn verify_proof_segment_sha_256_21() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn verify_proof_succinct() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 25_159_349_000 picoseconds.
        Weight::from_parts(25_393_350_000, 0)
    }
    fn verify_proof_segment_poseidon2_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 24_343_188_000 picoseconds.
        Weight::from_parts(24_451_349_000, 0)
    }
    fn verify_proof_segment_sha_256_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_302_386_000 picoseconds.
        Weight::from_parts(6_412_252_000, 0)
    }
    fn verify_proof_segment_poseidon2_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 26_093_897_000 picoseconds.
        Weight::from_parts(26_227_165_000, 0)
    }
    fn verify_proof_segment_sha_256_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_259_460_000 picoseconds.
        Weight::from_parts(6_296_064_000, 0)
    }
    fn verify_proof_segment_poseidon2_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 27_837_208_000 picoseconds.
        Weight::from_parts(27_973_141_000, 0)
    }
    fn verify_proof_segment_sha_256_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_616_839_000 picoseconds.
        Weight::from_parts(6_664_248_000, 0)
    }
    fn verify_proof_segment_poseidon2_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 29_479_589_000 picoseconds.
        Weight::from_parts(29_586_043_000, 0)
    }
    fn verify_proof_segment_sha_256_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_096_450_000 picoseconds.
        Weight::from_parts(7_156_530_000, 0)
    }
    fn verify_proof_segment_poseidon2_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 31_531_129_000 picoseconds.
        Weight::from_parts(31_663_007_000, 0)
    }
    fn verify_proof_segment_sha_256_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_778_163_000 picoseconds.
        Weight::from_parts(7_837_869_000, 0)
    }
    fn verify_proof_segment_poseidon2_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 33_735_360_000 picoseconds.
        Weight::from_parts(33_820_397_000, 0)
    }
    fn verify_proof_segment_sha_256_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_718_935_000 picoseconds.
        Weight::from_parts(7_777_177_000, 0)
    }
}