// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_ezkl_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-10-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-QR4H5RM`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/dimitris/current_sprint/zkVerify/target/production/zkv-relay
// benchmark
// pallet
// --runtime
// /home/dimitris/current_sprint/zkVerify/target/production/wbuild/volta-runtime/volta_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-ezkl-verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/dimitris/current_sprint/zkVerify/HEADER-APACHE2
// --output
// verifiers/ezkl/src/weight.rs
// --template
// /home/dimitris/current_sprint/zkVerify/relay-node/benchmarks/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ezkl_verifier`.
pub trait WeightInfo {
    fn verify_proof() -> Weight;
    fn get_vk() -> Weight;
    fn validate_vk() -> Weight;
    fn compute_statement_hash() -> Weight;
    fn register_vk() -> Weight;
    fn unregister_vk() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn verify_proof() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 0_000 picoseconds.
        Weight::from_parts(16_350_802_000, 0)
    }
    /// Storage: `SettlementEzklPallet::Vks` (r:1 w:0)
    /// Proof: `SettlementEzklPallet::Vks` (`max_values`: None, `max_size`: Some(9258), added: 11733, mode: `MaxEncodedLen`)
    fn get_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6373`
        //  Estimated: `12723`
        // Minimum execution time: 7_211_000 picoseconds.
        Weight::from_parts(7_701_000, 12723)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
    }
    fn validate_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 107_000 picoseconds.
        Weight::from_parts(120_000, 0)
    }
    fn compute_statement_hash() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 14_043_000 picoseconds.
        Weight::from_parts(14_401_000, 0)
    }
    /// Storage: `SettlementEzklPallet::Disabled` (r:1 w:0)
    /// Proof: `SettlementEzklPallet::Disabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `SettlementEzklPallet::Tickets` (r:1 w:1)
    /// Proof: `SettlementEzklPallet::Tickets` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
    /// Storage: `SettlementEzklPallet::Vks` (r:1 w:1)
    /// Proof: `SettlementEzklPallet::Vks` (`max_values`: None, `max_size`: Some(9258), added: 11733, mode: `MaxEncodedLen`)
    fn register_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `147`
        //  Estimated: `12723`
        // Minimum execution time: 52_098_000 picoseconds.
        Weight::from_parts(56_194_000, 12723)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    /// Storage: `SettlementEzklPallet::Tickets` (r:1 w:1)
    /// Proof: `SettlementEzklPallet::Tickets` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
    /// Storage: `SettlementEzklPallet::Vks` (r:1 w:1)
    /// Proof: `SettlementEzklPallet::Vks` (`max_values`: None, `max_size`: Some(9258), added: 11733, mode: `MaxEncodedLen`)
    fn unregister_vk() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6538`
        //  Estimated: `12723`
        // Minimum execution time: 35_922_000 picoseconds.
        Weight::from_parts(37_192_000, 12723)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}
