
// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_ultrahonk_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-10-21, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-QR4H5RM`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/dimitris/current_sprint/zkVerify/target/production/zkv-relay
// benchmark
// pallet
// --runtime
// /home/dimitris/current_sprint/zkVerify/target/production/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-ultrahonk-verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/dimitris/current_sprint/zkVerify/HEADER-APACHE2
// --output
// verifiers/ultrahonk/src/weight.rs
// --template
// /home/dimitris/current_sprint/zkVerify/relay-node/benchmarks/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ultrahonk_verifier`.
pub trait WeightInfo {
    fn verify_zk_proof_log_7() -> Weight;
    fn verify_plain_proof_log_7() -> Weight;
    fn verify_zk_proof_log_8() -> Weight;
    fn verify_plain_proof_log_8() -> Weight;
    fn verify_zk_proof_log_9() -> Weight;
    fn verify_plain_proof_log_9() -> Weight;
    fn verify_zk_proof_log_10() -> Weight;
    fn verify_plain_proof_log_10() -> Weight;
    fn verify_zk_proof_log_11() -> Weight;
    fn verify_plain_proof_log_11() -> Weight;
    fn verify_zk_proof_log_12() -> Weight;
    fn verify_plain_proof_log_12() -> Weight;
    fn verify_zk_proof_log_13() -> Weight;
    fn verify_plain_proof_log_13() -> Weight;
    fn verify_zk_proof_log_14() -> Weight;
    fn verify_plain_proof_log_14() -> Weight;
    fn verify_zk_proof_log_15() -> Weight;
    fn verify_plain_proof_log_15() -> Weight;
    fn verify_zk_proof_log_16() -> Weight;
    fn verify_plain_proof_log_16() -> Weight;
    fn verify_zk_proof_log_17() -> Weight;
    fn verify_plain_proof_log_17() -> Weight;
    fn verify_zk_proof_log_18() -> Weight;
    fn verify_plain_proof_log_18() -> Weight;
    fn verify_zk_proof_log_19() -> Weight;
    fn verify_plain_proof_log_19() -> Weight;
    fn verify_zk_proof_log_20() -> Weight;
    fn verify_plain_proof_log_20() -> Weight;
    fn verify_zk_proof_log_21() -> Weight;
    fn verify_plain_proof_log_21() -> Weight;
    fn verify_zk_proof_log_22() -> Weight;
    fn verify_plain_proof_log_22() -> Weight;
    fn verify_zk_proof_log_23() -> Weight;
    fn verify_plain_proof_log_23() -> Weight;
    fn verify_zk_proof_log_24() -> Weight;
    fn verify_plain_proof_log_24() -> Weight;
    fn verify_zk_proof_log_25() -> Weight;
    fn verify_plain_proof_log_25() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    fn verify_zk_proof_log_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_7() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_8() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_9() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_10() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_11() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_12() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_13() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_14() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_15() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_22() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_22() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_23() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_23() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_24() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_24() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_zk_proof_log_25() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
    fn verify_plain_proof_log_25() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 12_438_014_000 picoseconds.
        Weight::from_parts(14_808_597_000, 0)
    }
}
