// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_ultrahonk_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-QR4H5RM`, CPU: `Intel(R) Core(TM) Ultra 7 155H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/dimitris/current_sprint/zkVerify/target/production/zkv-relay
// benchmark
// pallet
// --runtime
// /home/dimitris/current_sprint/zkVerify/target/production/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-ultrahonk-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/dimitris/current_sprint/zkVerify/HEADER-APACHE2
// --output
// /home/dimitris/current_sprint/zkVerify/verifiers/ultrahonk/src/weight_verify_proof.rs
// --template
// /home/dimitris/current_sprint/zkVerify/relay-node/benchmarks/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_ultrahonk_verifier_verify_proof`.
pub trait WeightInfo {
    fn verify_zk_proof_v3_0(n: u32, ) -> Weight;
    fn verify_plain_proof_v3_0(n: u32, ) -> Weight;
    fn verify_zk_proof_v0_84() -> Weight;
    fn verify_plain_proof_v0_84() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// The range of component `n` is `[7, 25]`.
    fn verify_zk_proof_v3_0(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_567_255_000 picoseconds.
        Weight::from_parts(6_271_968_895, 0)
            // Standard Error: 1_868_245
            .saturating_add(Weight::from_parts(66_697_610, 0).saturating_mul(n.into()))
    }
    /// The range of component `n` is `[7, 25]`.
    fn verify_plain_proof_v3_0(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_677_098_000 picoseconds.
        Weight::from_parts(6_345_016_546, 0)
            // Standard Error: 2_042_332
            .saturating_add(Weight::from_parts(43_412_888, 0).saturating_mul(n.into()))
    }
    fn verify_zk_proof_v0_84() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_733_681_000 picoseconds.
        Weight::from_parts(8_918_319_000, 0)
    }
    fn verify_plain_proof_v0_84() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_351_139_000 picoseconds.
        Weight::from_parts(8_166_412_000, 0)
    }
}
