// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_risc0_verifier`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-02-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `3e4e135035a1`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-node
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-risc0-verifier
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/src/weights/pallet_risc0_verifier.rs
// --template
// /data/benchmark/node/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.N39xvPnWtj

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_risc0_verifier` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_risc0_verifier::WeightInfoVerifyProof for ZKVWeight<T> {
    fn verify_proof_succinct() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_16() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_16() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_17() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_17() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_18() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_18() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_19() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_19() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_20() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_20() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_poseidon2_21() -> Weight {
        Default::default()
    }

    fn verify_proof_segment_sha_256_21() -> Weight {
        Default::default()
    }
}
