// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_hyperbridge_aggregations`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2025-03-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bench1.fi`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/rdoria/zkVerify/target/production/zkv-relay
// benchmark
// pallet
// --runtime
// /home/rdoria/zkVerify/target/production/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-hyperbridge-aggregations
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/rdoria/zkVerify/HEADER-APACHE2
// --output
// /home/rdoria/zkVerify/runtime/src/weights/pallet_hyperbridge_aggregations.rs
// --template
// /home/rdoria/zkVerify/relay-node/benchmarks/zkv-deploy-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for `pallet_hyperbridge_aggregations` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_hyperbridge_aggregations::WeightInfo for ZKVWeight<T> {
    /// Storage: `Hyperbridge::HostParams` (r:1 w:0)
    /// Proof: `Hyperbridge::HostParams` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Ismp::Nonce` (r:1 w:1)
    /// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739c8a16614057a29b1c0ba37754f1` (r:1 w:1)
    /// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74739c8a16614057a29b1c0ba37754f1` (r:1 w:1)
    /// Storage: UNKNOWN KEY `0x526571756573745061796d656e749c8a16614057a29b1c0ba37754f1b0926cdc` (r:0 w:1)
    /// Proof: UNKNOWN KEY `0x526571756573745061796d656e749c8a16614057a29b1c0ba37754f1b0926cdc` (r:0 w:1)
    fn dispatch_aggregation() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `91`
        //  Estimated: `3593`
        // Minimum execution time: 38_793_000 picoseconds.
        Weight::from_parts(40_015_000, 3593)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}