// Copyright 2024, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_risc0_verifier_verify_proof`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-06-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `f159bb4e46d6`, CPU: `AMD Ryzen 7 7700 8-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /usr/local/bin/zkv-relay
// benchmark
// pallet
// --runtime
// /app/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-risc0-verifier-verify-proof
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /data/benchmark/HEADER-APACHE2
// --output
// /data/benchmark/runtime/src/weights/pallet_risc0_verifier_verify_proof.rs
// --template
// /data/benchmark/relay-node/benchmarks/zkv-deploy-weight-template.hbs
// --base-path=/tmp/tmp.VMRZkLxJb9

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::parachains;
use crate::weight_aliases::*;

/// Weights for `pallet_risc0_verifier_verify_proof` using the zkVerify node and recommended hardware.
pub struct ZKVWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> pallet_risc0_verifier_verify_proof::WeightInfo for ZKVWeight<T> {
    fn verify_proof_succinct() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 31_065_015_000 picoseconds.
        Weight::from_parts(31_106_344_000, 0)
    }
    fn verify_proof_segment_poseidon2_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 30_250_006_000 picoseconds.
        Weight::from_parts(30_283_378_000, 0)
    }
    fn verify_proof_segment_sha_256_16() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_202_657_000 picoseconds.
        Weight::from_parts(7_218_476_000, 0)
    }
    fn verify_proof_segment_poseidon2_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 32_667_157_000 picoseconds.
        Weight::from_parts(32_709_818_000, 0)
    }
    fn verify_proof_segment_sha_256_17() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_078_663_000 picoseconds.
        Weight::from_parts(7_098_049_000, 0)
    }
    fn verify_proof_segment_poseidon2_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 34_678_391_000 picoseconds.
        Weight::from_parts(34_722_053_000, 0)
    }
    fn verify_proof_segment_sha_256_18() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_477_195_000 picoseconds.
        Weight::from_parts(7_496_290_000, 0)
    }
    fn verify_proof_segment_poseidon2_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 36_755_621_000 picoseconds.
        Weight::from_parts(36_799_845_000, 0)
    }
    fn verify_proof_segment_sha_256_19() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_980_244_000 picoseconds.
        Weight::from_parts(7_997_516_000, 0)
    }
    fn verify_proof_segment_poseidon2_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 39_159_416_000 picoseconds.
        Weight::from_parts(39_208_969_000, 0)
    }
    fn verify_proof_segment_sha_256_20() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_706_353_000 picoseconds.
        Weight::from_parts(8_726_070_000, 0)
    }
    fn verify_proof_segment_poseidon2_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 42_082_110_000 picoseconds.
        Weight::from_parts(42_143_165_000, 0)
    }
    fn verify_proof_segment_sha_256_21() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_615_561_000 picoseconds.
        Weight::from_parts(8_645_668_000, 0)
    }
}
