[package]
name = "proof-of-existence-rpc-runtime-api"
version = "0.1.0"
description = "Add RPC commands to the Proof of Existence pallet - runtime side"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
pallet-poe         = { default-features = false, workspace = true }
codec              = { default-features = false, workspace = true, features = ["derive"] }
sp-api             = { default-features = false, workspace = true }
sp-std             = { default-features = false, workspace = true }
sp-core            = { default-features = false, workspace = true }
sp-runtime         = { default-features = false, workspace = true }
scale-info         = { default-features = false, workspace = true, features = ["derive", "serde"] }
serde              = { optional = true, workspace = true }

binary-merkle-tree = { default-features = false, workspace = true }

[features]
default = [ "std" ]
std = [
	"pallet-poe/std",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"scale-info/std",
	"binary-merkle-tree/std",
	"serde",
	"sp-core/std"
]
