// Copyright 2026, Horizen Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pallet_crl`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2026-02-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `drhorizen`, CPU: `11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// ./target/release/zkv-relay
// benchmark
// pallet
// --runtime
// target/release/wbuild/zkv-runtime/zkv_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --pallet
// pallet-crl
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --heap-pages=4096
// --header
// /home/daniele/horizen/git/zkVerify/HEADER-APACHE2
// --output
// pallets/crl/src/weight.rs
// --template
// /home/daniele/horizen/git/zkVerify/relay-node/benchmarks/zkv-pallets-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_crl`.
pub trait WeightInfo {
    fn register_ca() -> Weight;
    fn unregister_ca() -> Weight;
    fn update_crl(n: u32, ) -> Weight;
    fn clear_crl() -> Weight;
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2144), added: 4619, mode: `MaxEncodedLen`)
    fn register_ca() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `5609`
        // Minimum execution time: 24_428_000 picoseconds.
        Weight::from_parts(25_601_000, 5609)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    /// Storage: `Crl::CertificateAuthorities` (r:0 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2144), added: 4619, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(3240084), added: 3242559, mode: `MaxEncodedLen`)
    fn unregister_ca() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 16_860_000 picoseconds.
        Weight::from_parts(17_442_000, 0)
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::CertificateAuthorities` (r:1 w:1)
    /// Proof: `Crl::CertificateAuthorities` (`max_values`: None, `max_size`: Some(2144), added: 4619, mode: `MaxEncodedLen`)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(3240084), added: 3242559, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[1, 1000]`.
    fn update_crl(n: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `601`
        //  Estimated: `5609`
        // Minimum execution time: 5_534_807_000 picoseconds.
        Weight::from_parts(5_503_496_899, 5609)
            // Standard Error: 34_643
            .saturating_add(Weight::from_parts(1_891_034, 0).saturating_mul(n.into()))
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    /// Storage: `Crl::Revoked` (r:0 w:1)
    /// Proof: `Crl::Revoked` (`max_values`: None, `max_size`: Some(3240084), added: 3242559, mode: `MaxEncodedLen`)
    fn clear_crl() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 2_596_000 picoseconds.
        Weight::from_parts(2_777_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}
