name: Audit

run-name: "Workflow CI/CD Steps: cargo audit"

on:
  schedule:
    - cron: "0 1 * * SAT"  # Runs every Saturday 1:00 UTC
  workflow_call:
  workflow_dispatch:

jobs:
  audit:
    runs-on: warp-ubuntu-latest-x64-2x
    name: Cargo audit
    steps:
      - name: Git checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Cargo audit
        uses: ./.github/actions/cmd-in-docker
        with:
          command: "cargo audit 2>&1 | tee audit_output.txt"
          use_cache: 'no'
          cargo_binaries_install: cargo-audit

      - name: Upload cargo audit output
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: audit-output
          path: audit_output.txt
          retention-days: 7
          compression-level: 0
          overwrite: true

  # Slack notification if failed on scheduled run
  failure-notification:
    runs-on: warp-ubuntu-latest-x64-2x
    name: Notify if failed
    needs: [audit]
    if: ${{ failure() && !cancelled() && github.event_name == 'schedule' }}
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_ALERTS_ZKVERIFY }}
          webhook-type: incoming-webhook
          errors: true
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 zkVerify ALERT - ${{ github.workflow }} Job Failed! 🚨"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Job URL:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Job>"
                    }
                  ]
                }
              ]
            }
