name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      chain:
        description: "Solo or relay"
        required: true
        type: string
  workflow_call:
    inputs:
      chain:
        description: "Solo or relay"
        required: true
        type: string
env:
  DOCKER_HUB_ORG: horizenlabs
  DOCKER_IMAGE_BUILD_NAME: ${{ vars.DOCKER_IMAGE_BUILD_NAME }}

jobs:
  build:
    runs-on:
      group: ${{ vars.RUNNER_GROUP }}
    name: Build Docker image
    steps:
      - uses: actions/checkout@v4
      - id: create-docker-images
        uses: ./.github/actions/build-docker-image
        with:
          chain: ${{ inputs.chain }}
          ref: ${{ github.ref }}
          docker_hub_org: ${{ env.DOCKER_HUB_ORG }}
          docker_image_name: ${{ env.DOCKER_IMAGE_BUILD_NAME }}
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          ARTIFACT_NAME: ${{ steps.create-docker-images.outputs.artifact_name }}