name: Coverage

run-name: "Workflow CI/CD Steps: coverage"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: warp-ubuntu-latest-x64-8x
    name: Coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Cargo coverage
        uses: ./.github/actions/cmd-in-docker
        with:
          command: >-
            /bin/bash -c 'set -o pipefail && export CARGO_PROFILE_DEV_DEBUG=0 && cargo llvm-cov clean --workspace && find . -name \"*.profraw\" -delete
            && cargo llvm-cov --no-rustc-wrapper --all-features --workspace --exclude zkv-relay --exclude paratest-node --exclude test-service --lcov --output-path lcov.info
            && cargo llvm-cov report --json --output-path coverage_report.json --summary-only && cargo llvm-cov report | tee coverage_summary.txt'
          use_cache: 'yes'
          cache_key: 'coverage'
          cargo_binaries_install: cargo-llvm-cov

      - name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-output
          path: coverage_report.json
          retention-days: 1
          compression-level: 0
          overwrite: true
