name: Cache cleanup

run-name: Cache cleanup

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: warp-ubuntu-latest-x64-2x
    name: "Clear cache key: '${{ matrix.cache_key }}'"
    strategy:
      matrix:
        cache_key:
          - build-relay-paratest-zkverify
          - build-relay-paratest-volta
          - coverage-zkverify
          - coverage-volta
          - unit-test-zkverify
          - unit-test-volta
          - unit-test-no-features-zkverify
          - unit-test-no-features-volta
          - integration-test-zkverify
          - integration-test-volta
          - build-runtime-benchmarks-zkverify
          - build-runtime-benchmarks-volta
          - lint-output-zkverify
          - lint-output-volta
          - lint-format
          - udeps-zkverify
          - udeps-volta
          - build-try-runtime-zkverify
          - build-try-runtime-volta
          - rustdoc-zkverify
          - rustdoc-volta
    steps:
      - name: "Deleting '${{ matrix.cache_key }}' cache key"
        uses: WarpBuilds/cache@v1
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            deps/
          key: ${{ matrix.cache_key }}-${{ github.event.repository.default_branch }}
          delete-cache: true