name: Look for unused dependencies

run-name: "Workflow CI/CD Step: cargo udeps"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  udeps:
    runs-on: warp-ubuntu-latest-x64-8x
    name: Udeps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo udeps
        uses: ./.github/actions/cmd-in-docker
        with:
          image_tag: "noble_rust-nightly_latest"
          command: "cargo +nightly udeps --all-targets --all-features"
          use_cache: "yes"
          cache_key: "udeps"
          cargo_binaries_install: "cargo-udeps"
          lld_install: "yes"
