name: Zombienet-test

run-name: "Workflow CI/CD Steps: test on zombienet"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  zombienet-test:
    runs-on: warp-ubuntu-latest-x64-8x
    name: Zombienet test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download relay and paratest build binaries
        uses: actions/download-artifact@v4
        with:
          name: "relay-paratest-bins"
          path: target/release/

      - name: Make downloaded binaries executable
        shell: bash
        run: |
          chmod +x target/release/*

      - name: Yarn install and zombienet test
        uses: ./.github/actions/cmd-in-docker
        with:
          command: >-
            /bin/bash -c 'set -o pipefail && cd /build/zombienet-tests
            && yarn install
            && yarn test 2>&1 | tee /build/zombienet_test_output.txt'
          use_cache: 'no'
          cmake_install: 'yes'
          lld_install: 'yes'
          nodejs_version_install: '18'

      - name: Upload zombienet test results
        uses: actions/upload-artifact@v4
        with:
          name: zombienet-test-output
          path: zombienet_test_output.txt
          retention-days: 1
          compression-level: 0
          overwrite: true
